#!/usr/bin/env python3
# SimpleFPEWrapper - tools/gen_api_manifest.py
# Copyright (c) 2026 MobileGL-Dev
# SPDX-License-Identifier: LGPL-3.0-only
#
# Generates the resolver-surface API manifest (plans/03, task 3.5) by
# parsing lookup.cpp: every symbol eglGetProcAddress can answer, including
# aliases. Replaces the hand-written fpe_implementation_progress.yaml as
# the source of truth for "what does the wrapper export".
#
# Usage: gen_api_manifest.py <repo_root> <out_dir>
# Writes api-manifest.md and api-manifest.json into <out_dir>.
# TODO(plans/10, 10.6): diff against the gl.xml 2.1 profile in CI.

import json
import re
import sys
from pathlib import Path


def main() -> int:
    repo = Path(sys.argv[1])
    out_dir = Path(sys.argv[2])
    src = (repo / "SimpleFPEWrapper" / "lookup.cpp").read_text()

    direct = re.findall(r"^\s*GETPROC\((\w+), name\)", src, re.M)
    aliases = re.findall(
        r'std::strcmp\("(\w+)", name\) == 0\) \{\s*\n\s*return \(__eglMustCastToProperFunctionPointerType\)(\w+);',
        src,
    )

    entries = {name: {"status": "resolvable", "target": name} for name in direct}
    for alias, target in aliases:
        entries.setdefault(alias, {"status": "alias", "target": target})

    ordered = dict(sorted(entries.items()))
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "api-manifest.json").write_text(
        json.dumps({"source": "lookup.cpp", "count": len(ordered), "entries": ordered}, indent=1)
        + "\n"
    )

    lines = [
        "# SimpleFPEWrapper API manifest (resolver surface)",
        "",
        "Generated by `tools/gen_api_manifest.py` from `lookup.cpp` - do not edit.",
        f"Entries: {len(ordered)}",
        "",
        "| symbol | status | target |",
        "|---|---|---|",
    ]
    lines += [f"| {n} | {e['status']} | {e['target']} |" for n, e in ordered.items()]
    (out_dir / "api-manifest.md").write_text("\n".join(lines) + "\n")
    print(f"api manifest: {len(ordered)} entries -> {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
